services:
  staleflix:
    image: battermanz/staleflix:latest
    container_name: staleflix
    ports:
      - "9999:9999"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      TZ: Etc/UTC
    restart: unless-stopped